name: Build & Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    name: Build wheels (${{ matrix.os }} / py${{ matrix.python }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install ${{ matrix.python }}

      - name: Install cibuildwheel
        run: uv pip install cibuildwheel

      - name: Build wheels + run tests
        env:
          # выбираем нужные CPython ABI
          CIBW_BUILD: cp${{ matrix.python }}-*
          CIBW_SKIP: "*-musllinux_*"

          # pytest внутри wheel-окружения
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {project}/tests

        run: uv run cibuildwheel --output-dir dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-py${{ matrix.python }}
          path: dist/*

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/yamcot
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Build sdist
        run: uv build --sdist

      - name: Check build output
        run: ls -lh dist

      - name: Publish
        run: uv publish